-- Создание таблицы
create table if not exists dish
(
    id            integer generated by default as identity primary key,
    dish_name     varchar(30)      not null,
    calories      double precision not null,
    proteins      double precision,
    fats          double precision,
    carbohydrates double precision
);

-- Вставка тестовых данных
    INSERT INTO dish (dish_name, calories, proteins, fats, carbohydrates)
    VALUES
('Овсяная каша', 150.5, 5.0, 2.8, 27.3),
('Куриная грудка', 165.0, 31.0, 3.6, 0.0),
('Гречневая каша', 132.0, 4.5, 1.3, 25.0),
('Яичница', 215.0, 13.0, 17.0, 1.1),
('Творог 5%', 121.0, 17.0, 5.0, 3.0),
('Салат Цезарь', 350.0, 15.0, 25.0, 12.0),
('Лосось на гриле', 208.0, 20.0, 13.0, 0.0),
('Рис отварной', 130.0, 2.7, 0.3, 28.0),
('Овощной суп', 85.0, 2.0, 3.5, 10.0),
('Картофельное пюре', 106.0, 2.1, 3.3, 16.7),
('Шоколадный торт', 450.0, 5.0, 25.0, 55.0),
('Яблоко', 52.0, 0.3, 0.2, 14.0),
('Банан', 89.0, 1.1, 0.3, 22.8),
('Омлет с сыром', 210.0, 14.0, 16.0, 2.0),
('Тунец консервированный', 128.0, 29.0, 1.0, 0.0);

