create table if not exists dish
(
    id            integer generated by default as identity primary key,
    dish_name     varchar(30)      not null,
    calories      double precision not null,
    proteins      double precision,
    fats          double precision,
    carbohydrates double precision
)

