create table if not exists meal
(
    meal_id integer generated by default as identity primary key,
    person_id     integer not null references person on delete cascade,
    date          date,
    type          varchar(30)      not null,
    dish_id       integer          not null references dish on delete cascade,
    dish_weight   double precision not null,
    dish_calories double precision not null
)
-- Вставка тестовых данных
    INSERT INTO meal (person_id, date, type, dish_id, dish_weight, dish_calories)
    VALUES
(1, '2025-03-01', 'BREAKFAST', 1, 200, 301.0),
(1, '2025-03-01', 'LUNCH', 6, 250, 875.0),
(1, '2025-03-01', 'DINNER', 2, 150, 247.5),
(1, '2025-03-02', 'BREAKFAST', 4, 120, 258.0),
(1, '2025-03-02', 'ANOTHER', 12, 150, 78.0),
(1, '2025-03-03', 'LUNCH', 7, 200, 416.0),

(2, '2025-03-01', 'BREAKFAST', 5, 150, 181.5),
(2, '2025-03-01', 'LUNCH', 9, 300, 255.0),
(2, '2025-03-01', 'BREAKFAST', 1, 150, 225.75),
(2, '2025-03-02', 'DINNER', 15, 100, 128.0),
(2, '2025-03-02', 'ANOTHER', 13, 120, 106.8),
(2, '2025-03-02', 'LUNCH', 3, 200, 264.0),

(3, '2025-03-01', 'BREAKFAST', 14, 180, 378.0),
(3, '2025-03-01', 'LUNCH', 2, 200, 330.0),
(3, '2025-03-02', 'DINNER', 8, 250, 325.0),
(3, '2025-03-02', 'ANOTHER', 11, 80, 360.0),
(3, '2025-03-03', 'BREAKFAST', 4, 150, 322.5),
(3, '2025-03-03', 'LUNCH', 10, 300, 318.0),

(4, '2025-03-01', 'BREAKFAST', 1, 180, 270.9),
(4, '2025-03-01', 'DINNER', 7, 150, 312.0),
(4, '2025-03-02', 'BREAKFAST', 5, 100, 121.0),
(4, '2025-03-02', 'LUNCH', 6, 200, 700.0),
(4, '2025-03-02', 'ANOTHER', 12, 200, 104.0),
(4, '2025-03-02', 'DINNER', 3, 150, 198.0),

(5, '2025-03-01', 'BREAKFAST', 14, 200, 420.0),
(5, '2025-03-01', 'LUNCH', 2, 250, 412.5),
(5, '2025-03-01', 'DINNER', 15, 150, 192.0),
(5, '2025-03-01', 'ANOTHER', 13, 150, 133.5),
(5, '2025-03-02', 'BREAKFAST', 4, 180, 387.0),
(5, '2025-03-02', 'LUNCH', 7, 220, 457.6);

