create table if not exists meal
(
    meal_id integer generated by default as identity primary key,
    person_id     integer not null references person on delete cascade,
    date          date,
    type          varchar(30)      not null,
    dish_id       integer          not null references dish on delete cascade,
    dish_weight   double precision not null,
    dish_calories double precision not null
)

